name = "MyStatsPackage"
uuid = "e9345ce4-fb07-4b15-afa8-5e16e71e810e"
authors = ["philippreiser <philipp@fam-reiser.eu>"]
version = "0.1.0"

[deps]
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
